[workspace]
members = ["crates/*"]
resolver = "2"
# [dependencies]


[workspace.dependencies]
tracing = "0.1.41"
remind-core = { path = "crates/remind-core" }
serde = { version = "1.0.219", features = ["derive"] }
async-trait = "0.1.88"
uuid = "1.17.0"