services:
  db:
    image: postgres:16.2-alpine
    command: -p 5432
    expose:
      - 5432
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: