[package]
name = "remind-core"
edition = "2024"

[dependencies]
async-trait.workspace = true
sqlx = { version = "0.8.6", features = ["derive", "uuid", "runtime-tokio", "postgres", "migrate"] }
uuid.workspace = true
thiserror.workspace = true
remind-auth.workspace = true